/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'id' : string,
  'createdAt' : Time,
  'totalAmount' : number,
  'items' : Array<LineItem>,
}
export interface LineItem {
  'productName' : string,
  'barcode' : string,
  'quantity' : bigint,
  'unitPrice' : number,
  'totalPrice' : number,
}
export interface Product {
  'mrp' : number,
  'name' : string,
  'stock' : bigint,
  'barcode' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<[string, string, number, bigint], undefined>,
  'createBill' : ActorMethod<[Array<LineItem>], Bill>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBillHistory' : ActorMethod<[], Array<Bill>>,
  'getProduct' : ActorMethod<[string], Product>,
  'loadSampleData' : ActorMethod<[], undefined>,
  'updateProduct' : ActorMethod<[string, string, number, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];