/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LineItem = IDL.Record({
  'productName' : IDL.Text,
  'barcode' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'totalPrice' : IDL.Float64,
});
export const Time = IDL.Int;
export const Bill = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'totalAmount' : IDL.Float64,
  'items' : IDL.Vec(LineItem),
});
export const Product = IDL.Record({
  'mrp' : IDL.Float64,
  'name' : IDL.Text,
  'stock' : IDL.Nat,
  'barcode' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Nat], [], []),
  'createBill' : IDL.Func([IDL.Vec(LineItem)], [Bill], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBillHistory' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'loadSampleData' : IDL.Func([], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LineItem = IDL.Record({
    'productName' : IDL.Text,
    'barcode' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'totalPrice' : IDL.Float64,
  });
  const Time = IDL.Int;
  const Bill = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'totalAmount' : IDL.Float64,
    'items' : IDL.Vec(LineItem),
  });
  const Product = IDL.Record({
    'mrp' : IDL.Float64,
    'name' : IDL.Text,
    'stock' : IDL.Nat,
    'barcode' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Nat], [], []),
    'createBill' : IDL.Func([IDL.Vec(LineItem)], [Bill], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBillHistory' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'loadSampleData' : IDL.Func([], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };